# Generated by Django 4.2.7 on 2023-11-24 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ProjAppAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custompermission",
            name="slug",
        ),
        migrations.AddField(
            model_name="custompermission",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
