# Generated by Django 4.2.7 on 2023-11-24 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ProjAppAuth", "0002_remove_custompermission_slug_custompermission_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custompermission",
            name="uuid",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
